from __future__ import annotations

import asyncio
import json

from app.agent.execution_resume import register_executor

from .manager import configure_browser_use_manager
from .tools import (
    browser_back,
    browser_click,
    browser_console,
    browser_downloads,
    browser_evaluate,
    browser_extract_text,
    browser_fetch,
    browser_fill_form,
    browser_find,
    browser_forward,
    browser_full_page_screenshot,
    browser_get_element,
    browser_navigate,
    browser_network_summary,
    browser_open,
    browser_press,
    browser_reload,
    browser_screenshot,
    browser_scroll,
    browser_select_option,
    browser_session,
    browser_snapshot,
    browser_tabs,
    browser_type,
    browser_wait,
)


def register_browser_tools(registry, settings) -> None:
    manager = configure_browser_use_manager(settings)

    def _run_resume(coro) -> str:
        return asyncio.run(coro)

    def _resume_browser_click(input_str: str) -> str:
        args = json.loads(input_str or "{}")
        return _run_resume(
            browser_click(
                manager,
                ref=str(args.get("ref", "")),
                selector=str(args.get("selector", "")),
                text=str(args.get("text", "")),
                exact_text=bool(args.get("exact_text", False)),
                x=args.get("x"),
                y=args.get("y"),
                button=str(args.get("button", "left")),
                clicks=int(args.get("clicks", 1) or 1),
                tab_target_id=str(args.get("tab_target_id", "")),
                tab_index=int(args.get("tab_index", -1) or -1),
                wait_for_selector=str(args.get("wait_for_selector", "")),
                wait_for_text=str(args.get("wait_for_text", "")),
                wait_for_url_contains=str(args.get("wait_for_url_contains", "")),
                expect_new_tab=bool(args.get("expect_new_tab", False)),
                timeout_seconds=float(args.get("timeout_seconds", 10) or 10),
                _bypass_gate=True,
            )
        )

    def _resume_browser_type(input_str: str) -> str:
        args = json.loads(input_str or "{}")
        return _run_resume(
            browser_type(
                manager,
                text=str(args.get("text", "")),
                ref=str(args.get("ref", "")),
                selector=str(args.get("selector", "")),
                target_text=str(args.get("target_text", "")),
                exact_text=bool(args.get("exact_text", False)),
                submit=bool(args.get("submit", False)),
                clear=bool(args.get("clear", True)),
                tab_target_id=str(args.get("tab_target_id", "")),
                tab_index=int(args.get("tab_index", -1) or -1),
                verify_value=bool(args.get("verify_value", True)),
                wait_for_text=str(args.get("wait_for_text", "")),
                timeout_seconds=float(args.get("timeout_seconds", 10) or 10),
                _bypass_gate=True,
            )
        )

    def _resume_browser_downloads(input_str: str) -> str:
        args = json.loads(input_str or "{}")
        return _run_resume(
            browser_downloads(
                manager,
                action=str(args.get("action", "list")),
                _bypass_gate=True,
            )
        )

    register_executor("browser_click", _resume_browser_click)
    register_executor("browser_type", _resume_browser_type)
    register_executor("browser_downloads", _resume_browser_downloads)

    registry.extend(
        [
            {
                "name": "browser_session",
                "description": "Inspect, reset, stop, or switch the built-in browser-use session between managed and system Chrome modes.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "action": {
                            "type": "string",
                            "enum": ["status", "doctor", "list_profiles", "stop", "reset", "use_managed", "use_system"],
                            "default": "status",
                        },
                        "mode": {
                            "type": "string",
                            "enum": ["auto", "managed", "system"],
                            "default": "auto",
                        },
                        "profile_directory": {"type": "string", "default": ""},
                    },
                    "required": [],
                },
                "callable": lambda action="status", mode="auto", profile_directory="": browser_session(
                    manager,
                    action=action,
                    mode=mode,
                    profile_directory=profile_directory,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_open",
                "description": "Ensure a browser session exists, reusing an already-open matching tab before navigating the current tab unless reuse_existing is false.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "url": {"type": "string", "default": ""},
                        "mode": {"type": "string", "enum": ["auto", "managed", "system"], "default": "auto"},
                        "profile_directory": {"type": "string", "default": ""},
                        "new_tab": {"type": "boolean", "default": False},
                        "reuse_existing": {"type": "boolean", "default": True},
                        "wait_until": {"type": "string", "enum": ["domcontentloaded", "networkidle", "load"], "default": "domcontentloaded"},
                    },
                    "required": [],
                },
                "callable": lambda url="", mode="auto", profile_directory="", new_tab=False, reuse_existing=True, wait_until="domcontentloaded": browser_open(
                    manager,
                    url=url,
                    mode=mode,
                    profile_directory=profile_directory,
                    new_tab=new_tab,
                    reuse_existing=reuse_existing,
                    wait_until=wait_until,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_navigate",
                "description": "Navigate the current browser tab to a new URL.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "url": {"type": "string"},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                        "wait_until": {"type": "string", "enum": ["domcontentloaded", "networkidle", "load"], "default": "domcontentloaded"},
                    },
                    "required": ["url"],
                },
                "callable": lambda url, tab_target_id="", tab_index=-1, wait_until="domcontentloaded": browser_navigate(
                    manager,
                    url=url,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                    wait_until=wait_until,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_back",
                "description": "Go back in the current browser tab.",
                "parameters": {"type": "object", "properties": {}, "required": []},
                "callable": lambda: browser_back(manager),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_forward",
                "description": "Go forward in the current browser tab.",
                "parameters": {"type": "object", "properties": {}, "required": []},
                "callable": lambda: browser_forward(manager),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_reload",
                "description": "Reload the current browser tab.",
                "parameters": {"type": "object", "properties": {}, "required": []},
                "callable": lambda: browser_reload(manager),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_tabs",
                "description": "List, create, switch, or close browser tabs in the current browser-use session.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "action": {"type": "string", "enum": ["list", "new", "switch", "close"], "default": "list"},
                        "url": {"type": "string", "default": ""},
                        "target_id": {"type": "string", "default": ""},
                        "index": {"type": "integer", "default": -1},
                        "tab_index": {"type": "integer", "default": -1},
                        "mode": {"type": "string", "enum": ["auto", "managed", "system"], "default": "auto"},
                    },
                    "required": [],
                },
                "callable": lambda action="list", url="", target_id="", index=-1, tab_index=-1, mode="auto": browser_tabs(
                    manager,
                    action=action,
                    url=url,
                    target_id=target_id,
                    index=index,
                    tab_index=tab_index,
                    mode=mode,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_snapshot",
                "description": "Capture the current browser tab state and assign stable refs to visible interactive elements.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "include_screenshot": {"type": "boolean", "default": False},
                        "limit": {"type": "integer", "default": 40},
                        "mode": {"type": "string", "enum": ["auto", "managed", "system"], "default": "auto"},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                        "engine": {"type": "string", "enum": ["auto", "enhanced", "legacy"], "default": "auto"},
                        "include_tree": {"type": "boolean", "default": False},
                        "include_scroll_info": {"type": "boolean", "default": True},
                        "include_hidden_hints": {"type": "boolean", "default": True},
                    },
                    "required": [],
                },
                "callable": lambda include_screenshot=False, limit=40, mode="auto", tab_target_id="", tab_index=-1, engine="auto", include_tree=False, include_scroll_info=True, include_hidden_hints=True: browser_snapshot(
                    manager,
                    include_screenshot=include_screenshot,
                    limit=limit,
                    mode=mode,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                    engine=engine,
                    include_tree=include_tree,
                    include_scroll_info=include_scroll_info,
                    include_hidden_hints=include_hidden_hints,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_click",
                "description": "Click a browser element by ref, selector, visible text, or absolute page coordinates.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "ref": {"type": "string", "default": ""},
                        "selector": {"type": "string", "default": ""},
                        "text": {"type": "string", "default": ""},
                        "exact_text": {"type": "boolean", "default": False},
                        "x": {"type": "integer"},
                        "y": {"type": "integer"},
                        "button": {"type": "string", "enum": ["left", "right", "middle"], "default": "left"},
                        "clicks": {"type": "integer", "default": 1},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                        "wait_for_selector": {"type": "string", "default": ""},
                        "wait_for_text": {"type": "string", "default": ""},
                        "wait_for_url_contains": {"type": "string", "default": ""},
                        "expect_new_tab": {"type": "boolean", "default": False},
                        "timeout_seconds": {"type": "number", "default": 10},
                    },
                    "required": [],
                },
                "callable": lambda ref="", selector="", text="", exact_text=False, x=None, y=None, button="left", clicks=1, tab_target_id="", tab_index=-1, wait_for_selector="", wait_for_text="", wait_for_url_contains="", expect_new_tab=False, timeout_seconds=10: browser_click(
                    manager,
                    ref=ref,
                    selector=selector,
                    text=text,
                    exact_text=exact_text,
                    x=x,
                    y=y,
                    button=button,
                    clicks=clicks,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                    wait_for_selector=wait_for_selector,
                    wait_for_text=wait_for_text,
                    wait_for_url_contains=wait_for_url_contains,
                    expect_new_tab=expect_new_tab,
                    timeout_seconds=timeout_seconds,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_type",
                "description": "Fast-fill a browser input or editable element by stable ref, selector, or target_text. Uses direct DOM value insertion for long text and returns target metadata for verification.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "text": {"type": "string"},
                        "ref": {"type": "string", "default": ""},
                        "selector": {"type": "string", "default": ""},
                        "target_text": {"type": "string", "default": ""},
                        "exact_text": {"type": "boolean", "default": False},
                        "submit": {"type": "boolean", "default": False},
                        "clear": {"type": "boolean", "default": True},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                        "verify_value": {"type": "boolean", "default": True},
                        "wait_for_text": {"type": "string", "default": ""},
                        "timeout_seconds": {"type": "number", "default": 10},
                    },
                    "required": ["text"],
                },
                "callable": lambda text, ref="", selector="", target_text="", exact_text=False, submit=False, clear=True, tab_target_id="", tab_index=-1, verify_value=True, wait_for_text="", timeout_seconds=10: browser_type(
                    manager,
                    text=text,
                    ref=ref,
                    selector=selector,
                    target_text=target_text,
                    exact_text=exact_text,
                    submit=submit,
                    clear=clear,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                    verify_value=verify_value,
                    wait_for_text=wait_for_text,
                    timeout_seconds=timeout_seconds,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_press",
                "description": "Send a key press to the active browser tab.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "key": {"type": "string"},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                    },
                    "required": ["key"],
                },
                "callable": lambda key, tab_target_id="", tab_index=-1: browser_press(
                    manager,
                    key=key,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_select_option",
                "description": "Select one or more option values in a browser select element.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "values": {"type": "array", "items": {"type": "string"}},
                        "ref": {"type": "string", "default": ""},
                        "selector": {"type": "string", "default": ""},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                    },
                    "required": ["values"],
                },
                "callable": lambda values, ref="", selector="", tab_target_id="", tab_index=-1: browser_select_option(
                    manager,
                    values=values,
                    ref=ref,
                    selector=selector,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_scroll",
                "description": "Scroll the active browser tab by pixel deltas.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "delta_x": {"type": "integer", "default": 0},
                        "delta_y": {"type": "integer", "default": 800},
                        "x": {"type": "integer", "default": 0},
                        "y": {"type": "integer", "default": 0},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                    },
                    "required": [],
                },
                "callable": lambda delta_x=0, delta_y=800, x=0, y=0, tab_target_id="", tab_index=-1: browser_scroll(
                    manager,
                    delta_x=delta_x,
                    delta_y=delta_y,
                    x=x,
                    y=y,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_wait",
                "description": "Wait for time to pass or for a browser condition such as selector, visible text, or URL match.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "seconds": {"type": "number", "default": 0},
                        "selector": {"type": "string", "default": ""},
                        "text": {"type": "string", "default": ""},
                        "url_contains": {"type": "string", "default": ""},
                        "timeout_seconds": {"type": "number", "default": 10},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                    },
                    "required": [],
                },
                "callable": lambda seconds=0, selector="", text="", url_contains="", timeout_seconds=10, tab_target_id="", tab_index=-1: browser_wait(
                    manager,
                    seconds=seconds,
                    selector=selector,
                    text=text,
                    url_contains=url_contains,
                    timeout_seconds=timeout_seconds,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_find",
                "description": "Find visible browser elements by text, label, or role and return compact refs/metadata.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "text": {"type": "string", "default": ""},
                        "role": {"type": "string", "default": ""},
                        "label": {"type": "string", "default": ""},
                        "limit": {"type": "integer", "default": 20},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                    },
                    "required": [],
                },
                "callable": lambda text="", role="", label="", limit=20, tab_target_id="", tab_index=-1: browser_find(
                    manager,
                    text=text,
                    role=role,
                    label=label,
                    limit=limit,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
                "metadata": {"observation": True, "mutates_state": False, "risk_level": "low"},
            },
            {
                "name": "browser_get_element",
                "description": "Inspect one browser_snapshot ref and return cached enhanced DOM metadata plus current element state.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "ref": {"type": "string"},
                        "fields": {"type": "array", "items": {"type": "string"}, "default": []},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                    },
                    "required": ["ref"],
                },
                "callable": lambda ref, fields=None, tab_target_id="", tab_index=-1: browser_get_element(
                    manager,
                    ref=ref,
                    fields=fields,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
                "metadata": {"observation": True, "mutates_state": False, "risk_level": "low"},
            },
            {
                "name": "browser_fetch",
                "description": (
                    "Read-only fetch and extract a URL with Scrapling. Use for known URLs before opening a browser; "
                    "supports HTTP, dynamic rendered, and explicit stealth modes."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "url": {"type": "string"},
                        "mode": {"type": "string", "enum": ["auto", "http", "dynamic", "stealth"], "default": "auto"},
                        "selector": {"type": "string", "default": ""},
                        "output": {"type": "string", "enum": ["text", "markdown", "html", "links", "metadata"], "default": "text"},
                        "max_chars": {"type": "integer", "default": 20000},
                        "wait_selector": {"type": "string", "default": ""},
                        "network_idle": {"type": "boolean", "default": False},
                        "timeout_ms": {"type": "integer", "default": 30000},
                    },
                    "required": ["url"],
                },
                "callable": lambda url, mode="auto", selector="", output="text", max_chars=20000, wait_selector="", network_idle=False, timeout_ms=30000: browser_fetch(
                    manager,
                    url=url,
                    mode=mode,
                    selector=selector,
                    output=output,
                    max_chars=max_chars,
                    wait_selector=wait_selector,
                    network_idle=network_idle,
                    timeout_ms=timeout_ms,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
                "metadata": {
                    "observation": True,
                    "mutates_state": False,
                    "risk_level": "low",
                    "parallel_safe": True,
                    "resource_locks": [],
                    "repeat_safe": True,
                },
            },
            {
                "name": "browser_extract_text",
                "description": "Extract visible text from the page or a CSS selector.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "selector": {"type": "string", "default": ""},
                        "max_chars": {"type": "integer", "default": 20000},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                    },
                    "required": [],
                },
                "callable": lambda selector="", max_chars=20000, tab_target_id="", tab_index=-1: browser_extract_text(
                    manager,
                    selector=selector,
                    max_chars=max_chars,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
                "metadata": {"observation": True, "mutates_state": False, "risk_level": "low"},
            },
            {
                "name": "browser_fill_form",
                "description": "Fill multiple browser fields by refs/selectors and optionally click a submit control.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "fields": {"type": "array", "items": {"type": "object"}},
                        "submit_ref": {"type": "string", "default": ""},
                        "submit_selector": {"type": "string", "default": ""},
                        "wait_for_text": {"type": "string", "default": ""},
                        "timeout_seconds": {"type": "number", "default": 10},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                    },
                    "required": ["fields"],
                },
                "callable": lambda fields, submit_ref="", submit_selector="", wait_for_text="", timeout_seconds=10, tab_target_id="", tab_index=-1: browser_fill_form(
                    manager,
                    fields=fields,
                    submit_ref=submit_ref,
                    submit_selector=submit_selector,
                    wait_for_text=wait_for_text,
                    timeout_seconds=timeout_seconds,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_downloads",
                "description": "List or clear files in the managed browser downloads directory.",
                "parameters": {
                    "type": "object",
                    "properties": {"action": {"type": "string", "enum": ["list", "clear"], "default": "list"}},
                    "required": [],
                },
                "callable": lambda action="list": browser_downloads(manager, action=action),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_console",
                "description": "Read collected browser console diagnostics when available.",
                "parameters": {"type": "object", "properties": {}, "required": []},
                "callable": lambda: browser_console(manager),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_network_summary",
                "description": "Summarize recent browser resource timing entries for the active tab.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "limit": {"type": "integer", "default": 50},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                    },
                    "required": [],
                },
                "callable": lambda limit=50, tab_target_id="", tab_index=-1: browser_network_summary(
                    manager,
                    limit=limit,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_screenshot",
                "description": "Capture a screenshot of the current browser tab or a specific element ref/selector.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "ref": {"type": "string", "default": ""},
                        "selector": {"type": "string", "default": ""},
                        "format": {"type": "string", "enum": ["png", "jpeg", "webp"], "default": "png"},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                    },
                    "required": [],
                },
                "callable": lambda ref="", selector="", format="png", tab_target_id="", tab_index=-1: browser_screenshot(
                    manager,
                    ref=ref,
                    selector=selector,
                    format=format,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_full_page_screenshot",
                "description": (
                    "Capture a full-page browser screenshot. Optionally navigates to a URL first, "
                    "applies stealth-oriented init/runtime scripts, removes common fixed banners and popups, "
                    "and reports third-party archive/proxy fallbacks when the page remains blocked."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "url": {"type": "string", "default": ""},
                        "format": {"type": "string", "enum": ["png", "jpeg", "webp"], "default": "png"},
                        "mode": {"type": "string", "enum": ["auto", "managed", "system"], "default": "auto"},
                        "profile_directory": {"type": "string", "default": ""},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                        "stealth": {"type": "boolean", "default": True},
                        "declutter": {"type": "boolean", "default": True},
                        "remove_fixed": {"type": "boolean", "default": True},
                        "click_close": {"type": "boolean", "default": True},
                        "fallback_proxy": {
                            "type": "string",
                            "enum": ["none", "suggest", "archive_is", "smry_ai"],
                            "default": "suggest",
                            "description": (
                                "Use 'suggest' to return fallback URLs. Use archive_is or smry_ai only when "
                                "sending the current URL to that third-party proxy is acceptable."
                            ),
                        },
                    },
                    "required": [],
                },
                "callable": lambda url="", format="png", mode="auto", profile_directory="", tab_target_id="", tab_index=-1, stealth=True, declutter=True, remove_fixed=True, click_close=True, fallback_proxy="suggest": browser_full_page_screenshot(
                    manager,
                    url=url,
                    format=format,
                    mode=mode,
                    profile_directory=profile_directory,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                    stealth=stealth,
                    declutter=declutter,
                    remove_fixed=remove_fixed,
                    click_close=click_close,
                    fallback_proxy=fallback_proxy,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
            {
                "name": "browser_evaluate",
                "description": "Run JavaScript in the active browser tab. The script must be an arrow function like `(args) => ...`.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "script": {"type": "string"},
                        "args": {"type": "array", "items": {}},
                        "tab_target_id": {"type": "string", "default": ""},
                        "tab_index": {"type": "integer", "default": -1},
                    },
                    "required": ["script"],
                },
                "callable": lambda script, args=None, tab_target_id="", tab_index=-1: browser_evaluate(
                    manager,
                    script=script,
                    args=args,
                    tab_target_id=tab_target_id,
                    tab_index=tab_index,
                ),
                "domain": "browser",
                "execution_mode": "async",
                "affinity_group": "browser-use",
            },
        ]
    )
